apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"  # Sleep for 1 hour (adjust as needed)