version: '3'
services:
  fruit:
    image: kientree/fruit-service:1.0.0
  vegetables:
    image: kientree/vegetable-service:1.0.0
  all_products:
    image: kientree/all-products:1.0.0
    ports:
      - "8080:80"
    environment:
      - FRUIT_HOST=fruit
      - FRUIT_PORT=80
      - VEGETABLE_HOST=vegetables
      - VEGETABLE_PORT=80
